# Standards: 1.2
---
- name: Download repo key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
    state: present
  tags:
    - filebeat

- name: Add apt repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ filebeat_major_version }}.x/apt stable main"
    filename: elastic
    update_cache: True
    state: present
  tags:
    - filebeat

- name: Install required packages
  loop:
    - filebeat
  package:
    name: "{{ item }}"
    state: present
  tags:
    - filebeat

- name: Drop reference config
  file:
    path: /etc/filebeat/filebeat.reference.yml
    state: absent
  tags:
    - filebeat

- name: Drop modules dir
  file:
    path: /etc/filebeat/modules.d
    state: absent
  tags:
    - filebeat

- name: Write general config
  notify:
    - Restart filebeat
  template:
    src: config.j2
    dest: /etc/filebeat/filebeat.yml
    validate: filebeat test config -d -c %s
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - filebeat

- name: Start filebeat service
  systemd:
    name: filebeat
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - filebeat

...
