---
- name: Remove legacy key
  ansible.builtin.apt_key:
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
    state: absent
  tags:
    - filebeat

- name: Remove legacy repo
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ filebeat_major_version }}.x/apt stable main"
    filename: elastic
    update_cache: False
    state: absent
  tags:
    - filebeat

- name: Download repo key
  ansible.builtin.shell:
    cmd: "curl -sSL 'https://artifacts.elastic.co/GPG-KEY-elasticsearch' | gpg --dearmor --output {{ filebeat_keyring }}"
    creates: "{{ filebeat_keyring }}"
  tags:
    - filebeat

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ filebeat_keyring }}] https://artifacts.elastic.co/packages/{{ filebeat_major_version }}.x/apt stable main"
    filename: elastic
    update_cache: True
    state: present
  tags:
    - filebeat

- name: Install required packages
  loop:
    - filebeat
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - filebeat

- name: Drop reference config
  ansible.builtin.file:
    path: /etc/filebeat/filebeat.reference.yml
    state: absent
  tags:
    - filebeat

- name: Drop modules dir
  ansible.builtin.file:
    path: /etc/filebeat/modules.d
    state: absent
  tags:
    - filebeat

- name: Write general config
  notify:
    - Restart filebeat
  ansible.builtin.template:
    src: config.j2
    dest: /etc/filebeat/filebeat.yml
    validate: filebeat test config -d -c %s
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - filebeat

- name: Start filebeat service
  ansible.builtin.systemd:
    name: filebeat
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - filebeat

...
